// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/zone.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{0}
}

type ZoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneReq) Reset() {
	*x = ZoneReq{}
	mi := &file_proto_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneReq) ProtoMessage() {}

func (x *ZoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneReq.ProtoReflect.Descriptor instead.
func (*ZoneReq) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ZoneData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CodeName      string                 `protobuf:"bytes,2,opt,name=code_name,json=codeName,proto3" json:"code_name,omitempty"`
	ZoneFactor    float64                `protobuf:"fixed64,3,opt,name=zone_factor,json=zoneFactor,proto3" json:"zone_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneData) Reset() {
	*x = ZoneData{}
	mi := &file_proto_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneData) ProtoMessage() {}

func (x *ZoneData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneData.ProtoReflect.Descriptor instead.
func (*ZoneData) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{2}
}

func (x *ZoneData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneData) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *ZoneData) GetZoneFactor() float64 {
	if x != nil {
		return x.ZoneFactor
	}
	return 0
}

type ZoneRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CodeName      string                 `protobuf:"bytes,3,opt,name=code_name,json=codeName,proto3" json:"code_name,omitempty"`
	ZoneFactor    float64                `protobuf:"fixed64,4,opt,name=zone_factor,json=zoneFactor,proto3" json:"zone_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneRes) Reset() {
	*x = ZoneRes{}
	mi := &file_proto_zone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneRes) ProtoMessage() {}

func (x *ZoneRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneRes.ProtoReflect.Descriptor instead.
func (*ZoneRes) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{3}
}

func (x *ZoneRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ZoneRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneRes) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *ZoneRes) GetZoneFactor() float64 {
	if x != nil {
		return x.ZoneFactor
	}
	return 0
}

type ZoneList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*ZoneRes             `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneList) Reset() {
	*x = ZoneList{}
	mi := &file_proto_zone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneList) ProtoMessage() {}

func (x *ZoneList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneList.ProtoReflect.Descriptor instead.
func (*ZoneList) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{4}
}

func (x *ZoneList) GetZones() []*ZoneRes {
	if x != nil {
		return x.Zones
	}
	return nil
}

type DeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRes) Reset() {
	*x = DeleteRes{}
	mi := &file_proto_zone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRes) ProtoMessage() {}

func (x *DeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRes.ProtoReflect.Descriptor instead.
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateZoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CodeName      string                 `protobuf:"bytes,3,opt,name=code_name,json=codeName,proto3" json:"code_name,omitempty"`
	ZoneFactor    float64                `protobuf:"fixed64,4,opt,name=zone_factor,json=zoneFactor,proto3" json:"zone_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateZoneReq) Reset() {
	*x = UpdateZoneReq{}
	mi := &file_proto_zone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateZoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateZoneReq) ProtoMessage() {}

func (x *UpdateZoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_zone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateZoneReq.ProtoReflect.Descriptor instead.
func (*UpdateZoneReq) Descriptor() ([]byte, []int) {
	return file_proto_zone_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateZoneReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateZoneReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateZoneReq) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *UpdateZoneReq) GetZoneFactor() float64 {
	if x != nil {
		return x.ZoneFactor
	}
	return 0
}

var File_proto_zone_proto protoreflect.FileDescriptor

const file_proto_zone_proto_rawDesc = "" +
	"\n" +
	"\x10proto/zone.proto\x12\x04zone\x1a\x1egoogle/protobuf/wrappers.proto\"\a\n" +
	"\x05Empty\"\x19\n" +
	"\aZoneReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\\\n" +
	"\bZoneData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tcode_name\x18\x02 \x01(\tR\bcodeName\x12\x1f\n" +
	"\vzone_factor\x18\x03 \x01(\x01R\n" +
	"zoneFactor\"k\n" +
	"\aZoneRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcode_name\x18\x03 \x01(\tR\bcodeName\x12\x1f\n" +
	"\vzone_factor\x18\x04 \x01(\x01R\n" +
	"zoneFactor\"/\n" +
	"\bZoneList\x12#\n" +
	"\x05zones\x18\x01 \x03(\v2\r.zone.ZoneResR\x05zones\"%\n" +
	"\tDeleteRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"q\n" +
	"\rUpdateZoneReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcode_name\x18\x03 \x01(\tR\bcodeName\x12\x1f\n" +
	"\vzone_factor\x18\x04 \x01(\x01R\n" +
	"zoneFactor2\xf0\x01\n" +
	"\vZoneService\x12'\n" +
	"\bGetZones\x12\v.zone.Empty\x1a\x0e.zone.ZoneList\x12+\n" +
	"\vGetZoneByID\x12\r.zone.ZoneReq\x1a\r.zone.ZoneRes\x12+\n" +
	"\n" +
	"CreateZone\x12\x0e.zone.ZoneData\x1a\r.zone.ZoneRes\x120\n" +
	"\n" +
	"UpdateZone\x12\x13.zone.UpdateZoneReq\x1a\r.zone.ZoneRes\x12,\n" +
	"\n" +
	"DeleteZone\x12\r.zone.ZoneReq\x1a\x0f.zone.DeleteResB\tZ\a./protob\x06proto3"

var (
	file_proto_zone_proto_rawDescOnce sync.Once
	file_proto_zone_proto_rawDescData []byte
)

func file_proto_zone_proto_rawDescGZIP() []byte {
	file_proto_zone_proto_rawDescOnce.Do(func() {
		file_proto_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_zone_proto_rawDesc), len(file_proto_zone_proto_rawDesc)))
	})
	return file_proto_zone_proto_rawDescData
}

var file_proto_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_zone_proto_goTypes = []any{
	(*Empty)(nil),         // 0: zone.Empty
	(*ZoneReq)(nil),       // 1: zone.ZoneReq
	(*ZoneData)(nil),      // 2: zone.ZoneData
	(*ZoneRes)(nil),       // 3: zone.ZoneRes
	(*ZoneList)(nil),      // 4: zone.ZoneList
	(*DeleteRes)(nil),     // 5: zone.DeleteRes
	(*UpdateZoneReq)(nil), // 6: zone.UpdateZoneReq
}
var file_proto_zone_proto_depIdxs = []int32{
	3, // 0: zone.ZoneList.zones:type_name -> zone.ZoneRes
	0, // 1: zone.ZoneService.GetZones:input_type -> zone.Empty
	1, // 2: zone.ZoneService.GetZoneByID:input_type -> zone.ZoneReq
	2, // 3: zone.ZoneService.CreateZone:input_type -> zone.ZoneData
	6, // 4: zone.ZoneService.UpdateZone:input_type -> zone.UpdateZoneReq
	1, // 5: zone.ZoneService.DeleteZone:input_type -> zone.ZoneReq
	4, // 6: zone.ZoneService.GetZones:output_type -> zone.ZoneList
	3, // 7: zone.ZoneService.GetZoneByID:output_type -> zone.ZoneRes
	3, // 8: zone.ZoneService.CreateZone:output_type -> zone.ZoneRes
	3, // 9: zone.ZoneService.UpdateZone:output_type -> zone.ZoneRes
	5, // 10: zone.ZoneService.DeleteZone:output_type -> zone.DeleteRes
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_zone_proto_init() }
func file_proto_zone_proto_init() {
	if File_proto_zone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_zone_proto_rawDesc), len(file_proto_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_zone_proto_goTypes,
		DependencyIndexes: file_proto_zone_proto_depIdxs,
		MessageInfos:      file_proto_zone_proto_msgTypes,
	}.Build()
	File_proto_zone_proto = out.File
	file_proto_zone_proto_goTypes = nil
	file_proto_zone_proto_depIdxs = nil
}
