// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/zone.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZoneService_GetZones_FullMethodName    = "/zone.ZoneService/GetZones"
	ZoneService_GetZoneByID_FullMethodName = "/zone.ZoneService/GetZoneByID"
	ZoneService_CreateZone_FullMethodName  = "/zone.ZoneService/CreateZone"
	ZoneService_UpdateZone_FullMethodName  = "/zone.ZoneService/UpdateZone"
	ZoneService_DeleteZone_FullMethodName  = "/zone.ZoneService/DeleteZone"
)

// ZoneServiceClient is the client API for ZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneServiceClient interface {
	GetZones(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ZoneList, error)
	GetZoneByID(ctx context.Context, in *ZoneReq, opts ...grpc.CallOption) (*ZoneRes, error)
	CreateZone(ctx context.Context, in *ZoneData, opts ...grpc.CallOption) (*ZoneRes, error)
	UpdateZone(ctx context.Context, in *UpdateZoneReq, opts ...grpc.CallOption) (*ZoneRes, error)
	DeleteZone(ctx context.Context, in *ZoneReq, opts ...grpc.CallOption) (*DeleteRes, error)
}

type zoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneServiceClient(cc grpc.ClientConnInterface) ZoneServiceClient {
	return &zoneServiceClient{cc}
}

func (c *zoneServiceClient) GetZones(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ZoneList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZoneList)
	err := c.cc.Invoke(ctx, ZoneService_GetZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) GetZoneByID(ctx context.Context, in *ZoneReq, opts ...grpc.CallOption) (*ZoneRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZoneRes)
	err := c.cc.Invoke(ctx, ZoneService_GetZoneByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) CreateZone(ctx context.Context, in *ZoneData, opts ...grpc.CallOption) (*ZoneRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZoneRes)
	err := c.cc.Invoke(ctx, ZoneService_CreateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) UpdateZone(ctx context.Context, in *UpdateZoneReq, opts ...grpc.CallOption) (*ZoneRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZoneRes)
	err := c.cc.Invoke(ctx, ZoneService_UpdateZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) DeleteZone(ctx context.Context, in *ZoneReq, opts ...grpc.CallOption) (*DeleteRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRes)
	err := c.cc.Invoke(ctx, ZoneService_DeleteZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneServiceServer is the server API for ZoneService service.
// All implementations must embed UnimplementedZoneServiceServer
// for forward compatibility.
type ZoneServiceServer interface {
	GetZones(context.Context, *Empty) (*ZoneList, error)
	GetZoneByID(context.Context, *ZoneReq) (*ZoneRes, error)
	CreateZone(context.Context, *ZoneData) (*ZoneRes, error)
	UpdateZone(context.Context, *UpdateZoneReq) (*ZoneRes, error)
	DeleteZone(context.Context, *ZoneReq) (*DeleteRes, error)
	mustEmbedUnimplementedZoneServiceServer()
}

// UnimplementedZoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZoneServiceServer struct{}

func (UnimplementedZoneServiceServer) GetZones(context.Context, *Empty) (*ZoneList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZones not implemented")
}
func (UnimplementedZoneServiceServer) GetZoneByID(context.Context, *ZoneReq) (*ZoneRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZoneByID not implemented")
}
func (UnimplementedZoneServiceServer) CreateZone(context.Context, *ZoneData) (*ZoneRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZone not implemented")
}
func (UnimplementedZoneServiceServer) UpdateZone(context.Context, *UpdateZoneReq) (*ZoneRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateZone not implemented")
}
func (UnimplementedZoneServiceServer) DeleteZone(context.Context, *ZoneReq) (*DeleteRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteZone not implemented")
}
func (UnimplementedZoneServiceServer) mustEmbedUnimplementedZoneServiceServer() {}
func (UnimplementedZoneServiceServer) testEmbeddedByValue()                     {}

// UnsafeZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneServiceServer will
// result in compilation errors.
type UnsafeZoneServiceServer interface {
	mustEmbedUnimplementedZoneServiceServer()
}

func RegisterZoneServiceServer(s grpc.ServiceRegistrar, srv ZoneServiceServer) {
	// If the following call panics, it indicates UnimplementedZoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZoneService_ServiceDesc, srv)
}

func _ZoneService_GetZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GetZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GetZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GetZones(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_GetZoneByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GetZoneByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GetZoneByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GetZoneByID(ctx, req.(*ZoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_CreateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).CreateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_CreateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).CreateZone(ctx, req.(*ZoneData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_UpdateZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateZoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).UpdateZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_UpdateZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).UpdateZone(ctx, req.(*UpdateZoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_DeleteZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).DeleteZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_DeleteZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).DeleteZone(ctx, req.(*ZoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ZoneService_ServiceDesc is the grpc.ServiceDesc for ZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zone.ZoneService",
	HandlerType: (*ZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetZones",
			Handler:    _ZoneService_GetZones_Handler,
		},
		{
			MethodName: "GetZoneByID",
			Handler:    _ZoneService_GetZoneByID_Handler,
		},
		{
			MethodName: "CreateZone",
			Handler:    _ZoneService_CreateZone_Handler,
		},
		{
			MethodName: "UpdateZone",
			Handler:    _ZoneService_UpdateZone_Handler,
		},
		{
			MethodName: "DeleteZone",
			Handler:    _ZoneService_DeleteZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/zone.proto",
}
